# Generated by Django 4.2.16 on 2026-09-10 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="annual_accrual",
            field=models.IntegerField(
                default=0, help_text="Extra days per year of service"
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="carry_over",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="default_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="name_th",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="requires_advance_days",
            field=models.IntegerField(
                default=0, help_text="Business days in advance required"
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="entitled_days",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="year",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอการอนุมัติ"),
                    ("approved", "อนุมัติแล้ว"),
                    ("rejected", "ไม่อนุมัติ"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
